"""
Falsification test stubs for claim: "No more details in FAO pre-release
or release notes are relevant for existing concerns or ADRs"
Generated by /falsify on 2026-06-02

These tests verify that the postprocessor's output schema aligns with
the FAO-confirmed API contract from Release Note 01, Topic C.
"""


def test_falsify_fao_02_schema_country_identifier_m49_vs_iso_a3():
    """
    Probe 2 (Category H): FAO contract specifies UN M49; postprocessor uses ISO A3

    Finding: Release Note 01 Topic C states "PRIO/VIEWS will use UN M49
    as the standard country identifier." The postprocessor's _append_metadata
    enriches with 'country_iso_a3' (ISO Alpha-3). If the postprocessor output
    feeds into the API that FAO accesses, there is a coding system mismatch.

    This may be intentional (the postprocessor provides ISO A3 for internal use,
    and a separate API layer converts to M49) or it may be a gap. Either way,
    the relationship between the postprocessor's output and the FAO API contract
    is not documented in any ADR or CIC.

    Severity: Hard falsification (of the "no relevant details" claim)

    Expected: Either the postprocessor outputs M49, or an ADR documents
    the intentional divergence and where M49 conversion happens.
    """
    # TODO: Check whether the enriched DataFrame or the API layer
    # converts ISO A3 to UN M49 before FAO consumption.
    # If no conversion exists, the FAO receives ISO A3 when the
    # contract specifies M49.
    assert False, (
        "FAO contract specifies UN M49 as country identifier; "
        "postprocessor enriches with ISO A3 (country_iso_a3). "
        "No ADR documents the conversion or intentional divergence."
    )


def test_falsify_fao_02_schema_admin_field_names():
    """
    Probe 2 (Category H): FAO contract specifies ADM1_CODE; postprocessor uses admin1_gaul1_code

    Finding: Release Note 01 Topic C confirms GAUL field names:
    ADM1_CODE, ADM1_NAME, ADM2_CODE, ADM2_NAME. The postprocessor's
    filter_cols uses: admin1_gaul1_code, admin1_gaul1_name,
    admin2_gaul2_code, admin2_gaul2_name.

    Different naming conventions. If the postprocessor output feeds
    the API directly, the field names don't match the FAO contract.

    Severity: Hard falsification (of the "no relevant details" claim)

    Expected: Either the field names match the contract, or an ADR
    documents where the renaming happens.
    """
    assert False, (
        "FAO contract specifies ADM1_CODE/ADM2_CODE; "
        "postprocessor uses admin1_gaul1_code/admin2_gaul2_code. "
        "No ADR documents the mapping between these naming conventions."
    )


def test_falsify_fao_02_schema_coordinate_field_names():
    """
    Probe 2 (Category H): FAO contract specifies lat/lon; postprocessor uses pg_xcoord/pg_ycoord

    Finding: Release Note 01 Topic C states coordinates are provided as
    'lat' and 'lon'. The postprocessor's filter_cols uses 'pg_xcoord'
    and 'pg_ycoord'.

    Severity: Hard falsification (of the "no relevant details" claim)

    Expected: Either the field names match, or the renaming is documented.
    """
    assert False, (
        "FAO contract specifies lat/lon; "
        "postprocessor uses pg_xcoord/pg_ycoord. "
        "No ADR documents the mapping."
    )
