"""
Falsification test stubs for Campaign Claim 3.4:
"An integration test exists for the mapper-to-manager data path"
Generated by falsification campaign on 2026-06-02

READ-ONLY CAMPAIGN: These stubs document the missing integration test.
"""

import pytest

# Falsification probes assert known-open findings by design (assert False).
# Marked xfail(strict) so the suite is green-when-healthy and a probe that
# starts passing is surfaced for promotion. See C-36 in the risk register.
pytestmark = pytest.mark.xfail(reason="falsification probe — asserts a known-open finding by design (see reports/technical_risk_register.md, C-36); xfail(strict) keeps the suite green-when-healthy and surfaces any probe that starts passing", strict=True)


def test_falsify_3_4_no_mapper_to_manager_integration_test():
    """
    No test enriches a DataFrame through the mapper
    (enrich_dataframe_with_pg_info) and then checks the output against
    the manager's filter_cols list and null validation rules.

    The mapper and manager are tested in isolation. The boundary between
    them — where column names must match and nulls must be absent — has
    zero test coverage.

    Severity: Hard falsification
    """
    assert False, "No integration test for mapper-to-manager data path (enrich → filter_cols → validate)"
