"""
Falsification test stubs for round 3 re-audit of claim: "We 100% understand
the fundamental issues associated with Cluster B"
Generated by /falsify round 3 on 2026-06-02

Round 1: FALSIFIED (3 hard + 3 soft). Round 2: CONTESTED (1 hard + 3 soft).
Round 3: 2 hard falsifications found.

These tests are in TDD RED state -- they FAIL against the current code.
"""

import pytest


@pytest.mark.xfail(
    reason="falsification probe (C-06/C-20 — 7th zero-area guard site) — open "
           "finding; xfail(strict) keeps the suite green-when-healthy and "
           "surfaces it if the guard is added. See C-36 in the risk register.",
    strict=True,
)
def test_falsify_r3_03_dominant_gids_zero_area_guard_missing():
    """
    Probe 3 (Category B): _find_dominant_country_gids has no zero-area guard

    Finding: Line 927 computes overlap_ratio = intersection.area / grid_geometry.area
    in _find_dominant_country_gids (the reverse lookup). No zero-area guard exists.
    A degenerate cell raises ZeroDivisionError, caught by except Exception at
    line 932, logged at DEBUG, and silently excluded from the country's GID list.

    The same fix applied to 6 forward-lookup sites was missed here — the 7th
    overlap calculation site. This is C-06 (code duplication) materializing again.

    Severity: Hard falsification

    Expected: _find_dominant_country_gids has a zero-area guard before the division.
    """
    # TODO: Create a mapper with a zero-area cell in a known country's territory.
    # Call find_gids_for_country for that country.
    # Verify the zero-area cell is either included with a warning or explicitly
    # excluded with a warning — not silently dropped via caught ZeroDivisionError.
    assert False, "_find_dominant_country_gids line 927 has no zero-area guard — 7th site missed"


def test_falsify_r3_04_warnings_filterwarnings_still_global():
    """
    Probe 4 (Category D): warnings.filterwarnings("ignore") is still on line 26

    Finding: D-03 was resolved in the register with "replace with targeted
    warnings.catch_warnings() for CRS centroid warning." C-18 describes the
    problem. The resolution is a DECISION recorded in the register, but the
    CODE at line 26 is unchanged. The foundational cause of Cluster B — global
    warning suppression — has not been fixed.

    Severity: Hard falsification

    Expected: Line 26 no longer says warnings.filterwarnings("ignore").
    """
    # TODO: Import mapping.py module and check that:
    # (a) warnings.filters does NOT contain a global ("ignore", ...) entry
    #     from this module, AND
    # (b) the specific CRS centroid warning IS suppressed within _load_priogrid
    import warnings
    global_ignores = [f for f in warnings.filters if f[0] == "ignore" and f[2] is None]
    assert len(global_ignores) == 0, (
        "warnings.filterwarnings('ignore') still active globally — "
        "D-03 resolution not applied to code"
    )
