"""
Falsification test stubs for Campaign Claim 3.2:
"Validation tests cover all invalid input categories and match real _validate()"
Generated by falsification campaign on 2026-06-02

READ-ONLY CAMPAIGN: These stubs document test coverage gaps.

DISCHARGED 2026-08-02 (S4 / #185): `test_falsify_3_2_validation_uses_replica_not_real_code`
is removed — the replica it described is gone. `tests/test_validation.py` now tests
`contract/historical.assert_metadata_complete` directly, parametrised over the imported
`gaul_schema.METADATA_COLS`. Mutation-proven: narrowing the gate to one column fails 9 of
its 14 tests, where the replica-based suite passed that mutation untouched.

A probe written as `assert False` can never flip to XPASS, so the "surfaced for promotion"
mechanism below cannot reach it — a discharged probe has to be retired by hand, and leaving
one in place asserts a defect that no longer exists.
"""

import pytest

# Falsification probes assert known-open findings by design (assert False).
# Marked xfail(strict) so the suite is green-when-healthy and a probe that
# starts passing is surfaced for promotion. See C-36 in the risk register.
pytestmark = pytest.mark.xfail(reason="falsification probe — asserts a known-open finding by design (see reports/technical_risk_register.md, C-36); xfail(strict) keeps the suite green-when-healthy and surfaces any probe that starts passing", strict=True)


def test_falsify_3_2_wrong_type_columns_not_tested():
    """
    No test passes a DataFrame where a numeric column (e.g., admin1_gaul1_code)
    contains strings, or where a string column contains numbers. The validation
    only checks presence and nulls, not types — but this is still an untested
    category of invalid input.

    Severity: Soft falsification
    """
    assert False, "No test for wrong-type column values (e.g., string in numeric column)"

