"""
Falsification test stubs for Campaign Claim 3.5:
"An end-to-end pipeline test exists or can be constructed"
Generated by falsification campaign on 2026-06-02

READ-ONLY CAMPAIGN: These stubs document the missing E2E test.
"""

import pytest

# Falsification probes assert known-open findings by design (assert False).
# Marked xfail(strict) so the suite is green-when-healthy and a probe that
# starts passing is surfaced for promotion. See C-36 in the risk register.
pytestmark = pytest.mark.xfail(reason="falsification probe — asserts a known-open finding by design (see reports/technical_risk_register.md, C-36); xfail(strict) keeps the suite green-when-healthy and surfaces any probe that starts passing", strict=True)


def test_falsify_3_5_no_end_to_end_pipeline_test():
    """
    No test exercises the full pipeline: _read() → _transform() → _validate() → _save().

    views-pipeline-core is not installed in the test environment, making it
    impossible to instantiate UNFAOPostProcessorManager directly. An E2E test
    would require either: (a) installing views-pipeline-core in test env,
    (b) mocking the parent classes, or (c) testing the pipeline stages in
    sequence using the real code with mocked data sources.

    The pipeline orchestration — the thing that runs in production — has
    zero test coverage as an integrated unit.

    Severity: Hard falsification
    """
    assert False, "No end-to-end pipeline test (read→transform→validate→save)"
