"""
Falsification test stubs for Campaign Claim 3.5:
"An end-to-end pipeline test exists or can be constructed"
Generated by falsification campaign on 2026-06-02

READ-ONLY CAMPAIGN: These stubs document the missing E2E test.
"""


def test_falsify_3_5_no_end_to_end_pipeline_test():
    """
    No test exercises the full pipeline: _read() → _transform() → _validate() → _save().

    views-pipeline-core is not installed in the test environment, making it
    impossible to instantiate UNFAOPostProcessorManager directly. An E2E test
    would require either: (a) installing views-pipeline-core in test env,
    (b) mocking the parent classes, or (c) testing the pipeline stages in
    sequence using the real code with mocked data sources.

    The pipeline orchestration — the thing that runs in production — has
    zero test coverage as an integrated unit.

    Severity: Hard falsification
    """
    assert False, "No end-to-end pipeline test (read→transform→validate→save)"
