"""
Falsification test stubs for Campaign Claim 4.1:
"CI runs tests on every push and failure blocks merge"
Generated by falsification campaign on 2026-06-02
"""


def test_falsify_4_1_ci_not_confirmed_as_required_check():
    """
    run_pytest.yml runs on push to main/development and the pytest step
    is active with set -e. But whether this workflow is a REQUIRED status
    check in GitHub branch protection settings cannot be verified from
    the repo alone. A failing test would fail the workflow but might not
    block a merge if the check isn't marked as required.

    Severity: Soft falsification
    """
    assert False, "Cannot verify from repo that run_pytest is a required status check for PR merges"
