"""
Falsification test stubs for round 4 re-audit of claim: "We 100% understand
the fundamental issues associated with Cluster B"
Generated by /falsify round 4 on 2026-06-02

Rounds: R1 FALSIFIED (3H/3S) → R2 CONTESTED (1H/3S) → R3 FALSIFIED (2H/0S) → R4 below.

These tests are in TDD RED state -- they FAIL against the current code.
"""


def test_falsify_r4_01_make_valid_not_applied_to_load_methods():
    """
    Probe 1 (Category H): make_valid() resolved in D-04 but never applied to code

    Finding: D-04 was resolved with "Apply make_valid() at load time in all
    three _load_* methods." The Cluster B fix strategy explicitly includes
    "make_valid() preprocessing." C-12 notes the validate-then-proceed-anyway
    pattern. Zero make_valid() calls exist in the code.

    This is the third instance of register-to-code drift:
    - D-03 (warnings): resolved round 2, found unfixed round 3, then fixed
    - D-04 (make_valid): resolved round 2, found unfixed round 4

    Severity: Hard falsification

    Expected: _load_and_preprocess_naturalearth, _load_priogrid, and
    _load_admin_data each call make_valid() on loaded geometries.
    """
    # TODO: After applying make_valid(), verify:
    # (a) countries_gdf.geometry.is_valid.all() == True after loading
    # (b) priogrid_gdf.geometry.is_valid.all() == True after loading
    # (c) admin1_gdf.geometry.is_valid.all() == True after loading
    # (d) admin2_gdf.geometry.is_valid.all() == True after loading
    assert False, "make_valid() resolved in D-04 but zero calls in code — register-to-code drift"
