"""
Falsification test stubs for Campaign Claim 3.4:
"An integration test exists for the mapper-to-manager data path"
Generated by falsification campaign on 2026-06-02

READ-ONLY CAMPAIGN: These stubs document the missing integration test.
"""


def test_falsify_3_4_no_mapper_to_manager_integration_test():
    """
    No test enriches a DataFrame through the mapper
    (enrich_dataframe_with_pg_info) and then checks the output against
    the manager's filter_cols list and null validation rules.

    The mapper and manager are tested in isolation. The boundary between
    them — where column names must match and nulls must be absent — has
    zero test coverage.

    Severity: Hard falsification
    """
    assert False, "No integration test for mapper-to-manager data path (enrich → filter_cols → validate)"
