"""
Falsification test stubs for Campaign Claim 4.3:
"Schema change would fail a test"
Generated by falsification campaign on 2026-06-02

DISCHARGED 2026-08-02 (S4 / #185): `test_falsify_4_3_filter_cols_change_not_detected_by_validation_tests`
is removed. The hardcoded `REQUIRED_METADATA_COLS` replica it described is gone;
`tests/test_validation.py` parametrises over the imported `gaul_schema.METADATA_COLS`, so
adding a column to the declared contract extends the gate's coverage automatically — the
property register C-70 was resolved to give us.

`test_falsify_4_3_enrichment_test_checks_only_5_of_9_filter_cols` is removed for the same
reason, verified in the same pass. It described `test_enrichment` asserting 5 of the 9
contract columns. That file now imports `METADATA_COLS` and asserts
`list(lookup.columns) == METADATA_COLS` — exact equality on all nine — then iterates the
full set again for presence and for nulls. The four columns the probe said had "no schema
drift protection" are covered three times over.

**Claim 4.3 is therefore fully discharged and this module holds no live probe.** It is kept
rather than deleted because the campaign record is the point: it says what was checked on
2026-06-02, what was wrong, and when each finding was closed.
"""

import pytest

# Falsification probes assert known-open findings by design (assert False).
# Marked xfail(strict) so the suite is green-when-healthy and a probe that
# starts passing is surfaced for promotion. See C-36 in the risk register.
pytestmark = pytest.mark.xfail(reason="falsification probe — asserts a known-open finding by design (see reports/technical_risk_register.md, C-36); xfail(strict) keeps the suite green-when-healthy and surfaces any probe that starts passing", strict=True)


