"""
Falsification test stubs for Campaign Claim 3.2:
"Validation tests cover all invalid input categories and match real _validate()"
Generated by falsification campaign on 2026-06-02

READ-ONLY CAMPAIGN: These stubs document test coverage gaps.
"""


def test_falsify_3_2_wrong_type_columns_not_tested():
    """
    No test passes a DataFrame where a numeric column (e.g., admin1_gaul1_code)
    contains strings, or where a string column contains numbers. The validation
    only checks presence and nulls, not types — but this is still an untested
    category of invalid input.

    Severity: Soft falsification
    """
    assert False, "No test for wrong-type column values (e.g., string in numeric column)"


def test_falsify_3_2_validation_uses_replica_not_real_code():
    """
    test_validation.py uses a standalone validate_dataframe() function that
    replicates the logic from UNFAOPostProcessorManager._validate(). If the
    real _validate() changes (e.g., adds a new column to the required list),
    the replica won't be updated and tests will pass while production fails.

    This is a structural test-code coupling gap, not a missing test case.

    Severity: Soft falsification
    """
    assert False, "Validation tests use replicated logic, not the real _validate() method — divergence risk"
