"""
Falsification test stubs for Campaign Claim 4.3:
"Schema change would fail a test"
Generated by falsification campaign on 2026-06-02
"""

import pytest

# Falsification probes assert known-open findings by design (assert False).
# Marked xfail(strict) so the suite is green-when-healthy and a probe that
# starts passing is surfaced for promotion. See C-36 in the risk register.
pytestmark = pytest.mark.xfail(reason="falsification probe — asserts a known-open finding by design (see reports/technical_risk_register.md, C-36); xfail(strict) keeps the suite green-when-healthy and surfaces any probe that starts passing", strict=True)


def test_falsify_4_3_enrichment_test_checks_only_5_of_9_filter_cols():
    """
    test_enrichment_adds_expected_columns checks 5 columns:
    country_iso_a3, admin1_gaul1_code, admin1_gaul1_name,
    admin2_gaul2_code, admin2_gaul2_name.

    But filter_cols in unfao.py has 9 columns (also: pg_xcoord, pg_ycoord,
    admin1_gaul0_code, admin1_gaul0_name). Removing the missing 4 from
    either side would not fail any test.

    Severity: Soft falsification
    """
    assert False, "Enrichment schema test checks 5 of 9 filter_cols — 4 columns have no schema drift protection"


def test_falsify_4_3_filter_cols_change_not_detected_by_validation_tests():
    """
    The validation tests use a hardcoded REQUIRED_METADATA_COLS list that
    replicates unfao.py's _necessary_metadata_cols. If someone adds or
    removes a column from unfao.py's list, the test replica is not
    automatically updated — the tests continue to pass against the old list.

    Severity: Soft falsification
    """
    assert False, "Validation test's column list is a replica — adding/removing a column in unfao.py is not caught"
