"""
Falsification test stubs for Campaign Claim 1.1:
"The PriogridCountryMapper CIC §3-6 accurately describes actual behavior"
Generated by falsification campaign on 2026-06-02

READ-ONLY CAMPAIGN: These stubs document CIC-code discrepancies.
Source code is NOT modified. CIC should be updated to match reality.
"""


def test_falsify_1_1_01_cache_mode_guarantee_contradicted_by_c05():
    """
    Probe 1 (Category B): CIC §3 guarantees cache mode doesn't affect results.
    C-05 documents that batch_country_mapping, batch_admin_mapping,
    find_multiple_countries_by_iso_a3, clear_cache, and get_cache_stats
    all crash with AttributeError in disk-cache mode.

    A crash IS a different result than a successful return.
    The CIC guarantee is unconditional but false for these methods.

    Severity: Hard falsification
    CIC should: add caveat listing the C-05 broken methods.
    """
    assert False, "CIC §3 cache guarantee is unconditional but C-05 methods crash in disk mode"


def test_falsify_1_1_02_find_country_for_gid_returns_170_keys_not_4():
    """
    Probe 2 (Category B): CIC §5 says find_country_for_gid returns dict with
    iso_a3, country_name, overlap_ratio, method. Actual code (lines 688-691)
    dumps ALL Natural Earth columns (~170 keys) into the result dict.

    The documented return type is dramatically narrower than reality.

    Severity: Hard falsification
    CIC should: document that the return dict includes all shapefile columns,
    or the code should be changed to return only the documented keys.
    """
    assert False, "find_country_for_gid returns ~170 keys, CIC documents 4"


def test_falsify_1_1_03_cic_says_warning_code_uses_debug():
    """
    Probe 3 (Category B): CIC §6 says intersection failures are
    "logged as WARNING." Actual code at 7 sites uses logger.debug.
    DEBUG is invisible in production.

    Severity: Hard falsification
    CIC should: either say DEBUG (matching code) or code should be
    changed to WARNING (matching CIC). Currently they disagree.
    """
    assert False, "CIC §6 says WARNING for intersection failures; code uses DEBUG at 7 sites"


def test_falsify_1_1_06_find_admin1_returns_undocumented_keys():
    """
    Probe 6 (Category B): CIC §5 says find_admin1_for_gid returns dict with
    gaul1_code, gaul1_name, iso3_code, method. Actual code also returns
    gaul0_code, gaul0_name, continent, disp_en when available.

    Severity: Soft falsification
    CIC should: list all possible return keys, or note "additional GAUL
    fields may be present."
    """
    assert False, "find_admin1_for_gid returns 4 undocumented extra keys (gaul0_code, gaul0_name, continent, disp_en)"
