"""
Falsification test stubs for round 2 of splash zone claim: "We 100%
understand the impacts and splash zone associated with Cluster B"
Generated by /falsify on 2026-06-02

Round 1: FALSIFIED (1H/2S). Round 2 below.
"""


def test_falsify_szr2_03_cache_violates_cic_determinism():
    """
    Probe 3 (Category H): Disk cache makes pipeline non-reproducible

    Finding: The PriogridCountryMapper CIC guarantees "deterministic
    assignment given the same input shapefiles." But two machines with
    different cache states (one warm with stale entries, one cold)
    processing identical inputs with identical shapefiles will produce
    different output. The register describes stale cache (C-14) but
    never connects it to the CIC's determinism guarantee.

    Severity: Soft falsification

    Expected: The register or CIC explicitly notes that determinism
    holds only when cache state is equivalent, or the cache invalidation
    mechanism ensures cache state cannot diverge.
    """
    # TODO: Create two mapper instances with different cache states
    # (one pre-populated with a stale entry, one cold).
    # Process the same GID. Verify they return the same result.
    # Currently they won't — the stale cache returns the old answer.
    assert False, "Disk cache state violates CIC determinism guarantee across environments"


def test_falsify_szr2_04_validate_cannot_catch_misassignment():
    """
    Probe 4 (Category B): _validate() is structurally blind to wrong-but-valid assignments

    Finding: _validate() checks column presence and null counts. When
    Cluster B misassigns a cell (e.g., assigns "NGA" instead of "TCD"),
    the ISO code is valid, the column is present, the value is non-null.
    Validation passes. The safety net has a hole shaped like the exact
    failure mode it's supposed to catch.

    C-12 says "undetectable from the output" which covers this at a
    high level, but the specific gap between what _validate() checks
    (structural completeness) and what Cluster B produces (wrong-but-valid
    values) is not explicitly stated.

    Severity: Soft falsification

    Expected: The register explicitly notes that _validate() cannot
    catch Cluster B's primary failure mode (wrong-but-valid assignments).
    """
    # TODO: Create a DataFrame where country_iso_a3 is "NGA" for a cell
    # that should be "TCD". Run _validate(). Verify it passes.
    # This demonstrates the structural gap.
    assert False, "_validate() passes for wrong-but-valid assignments — Cluster B's primary impact is invisible to the safety net"
